# Generated by Django 3.0 on 2019-12-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happiness', models.IntegerField(default=5)),
                ('introvert', models.BooleanField(default=False)),
                ('mbti', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='phonebook.Personality'),
        ),
    ]
